---
title: "2025 NFL Draft ED Grades"
output:
  html_document:
    df_print: paged
---

```{r}
library(tidyverse)
```


```{r}
ED_Stats <- read.csv("ED_Rankings.csv") %>%
  arrange(rank) %>%
  mutate(pos_rank_bef = row_number())
ED_Stats
```


get means
```{r}
mean(ED_Stats$pass_grade)
mean(ED_Stats$run_grade)
mean(ED_Stats$pass_win)
mean(ED_Stats$run_stop)
mean(ED_Stats$prp)
```


```{r}
get_ed_values <- function(input_df) {
  df_ed_copy <- input_df %>% mutate(
    pass_grade = round(pmax(pmin((pass_grade-70) / 2, 10), 0), 2),  # Scale, cap at 10, floor at 0, 70-90
    run_grade = round(pmax(pmin((run_grade-65) / 2, 10), 0), 2), # Scale, cap at 10, floor at 0, 65-85
    pass_win = round(pmax(pmin((pass_win-10), 10), 0), 2), # 10-20
    run_stop = round(pmax(pmin((run_stop-4)*2, 10), 0), 2), # 4-9
    prp = round(pmax(pmin((prp-6)*1.67, 10), 0), 2), # 6-12
    
  )
  
  return(df_ed_copy)
}
```


```{r}
new_stats_ed <- get_ed_values(ED_Stats) %>% 
  mutate(total = rowSums(select(., -player, -adp, -rank, -pos_rank_bef, -team))) %>% 
  arrange(-total) %>%
  mutate(pos = "ED", pos_rank_aft = row_number(), pos_rank_diff = pos_rank_bef-pos_rank_aft) %>%
  select(player, pass_grade, run_grade, pass_win, run_stop, prp, total, rank, pos, team, pos_rank_bef, pos_rank_aft, pos_rank_diff)
new_stats_ed
```

get the dataset that only contains the total and the ranks
```{r}
ed_stats_total <- new_stats_ed %>%
  select(player, total, rank, pos, team, pos_rank_bef, pos_rank_aft, pos_rank_diff)
ed_stats_total
```